#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker-db"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "233433d7b4c74e1e815ee311398f3541" }
]

[assets]
directory = "./public"
